-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE public.building_id_seq;

CREATE SEQUENCE public.building_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.classroom_id_seq;

CREATE SEQUENCE public.classroom_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.faculty_id_seq;

CREATE SEQUENCE public.faculty_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.lesson_id_seq;

CREATE SEQUENCE public.lesson_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.roles_id_seq;

CREATE SEQUENCE public.roles_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.schedule_id_seq;

CREATE SEQUENCE public.schedule_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.student_group_id_seq;

CREATE SEQUENCE public.student_group_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.student_id_seq;

CREATE SEQUENCE public.student_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.subgroup_id_seq;

CREATE SEQUENCE public.subgroup_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.subject_id_seq;

CREATE SEQUENCE public.subject_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.teacher_id_seq;

CREATE SEQUENCE public.teacher_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.time_slot_id_seq;

CREATE SEQUENCE public.time_slot_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.user_sequence;

CREATE SEQUENCE public.user_sequence
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.building definition

-- Drop table

-- DROP TABLE public.building;

CREATE TABLE public.building (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address varchar(255) NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT building_name_key UNIQUE (name),
	CONSTRAINT building_pkey PRIMARY KEY (id)
);


-- public.faculty definition

-- Drop table

-- DROP TABLE public.faculty;

CREATE TABLE public.faculty (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	logo varchar(255) NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT faculty_name_key UNIQUE (name),
	CONSTRAINT faculty_pkey PRIMARY KEY (id)
);


-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT roles_name_check CHECK (((name)::text = ANY ((ARRAY['PROFESSOR'::character varying, 'STUDENT'::character varying, 'ADMIN'::character varying])::text[]))),
	CONSTRAINT roles_name_key UNIQUE (name),
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);


-- public.schedule definition

-- Drop table

-- DROP TABLE public.schedule;

CREATE TABLE public.schedule (
	"year" int4 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	semester varchar(255) NULL,
	CONSTRAINT schedule_pkey PRIMARY KEY (id)
);


-- public.subject definition

-- Drop table

-- DROP TABLE public.subject;

CREATE TABLE public.subject (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	CONSTRAINT subject_name_key UNIQUE (name),
	CONSTRAINT subject_pkey PRIMARY KEY (id),
	CONSTRAINT subject_type_check CHECK (((type)::text = ANY ((ARRAY['COURSE'::character varying, 'LABORATORY'::character varying, 'SEMINAR'::character varying, 'EXAM'::character varying, 'PROJECT'::character varying])::text[])))
);


-- public.time_slot definition

-- Drop table

-- DROP TABLE public.time_slot;

CREATE TABLE public.time_slot (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	day_of_week varchar(255) NOT NULL,
	end_time varchar(255) NOT NULL,
	start_time varchar(255) NOT NULL,
	CONSTRAINT time_slot_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[]))),
	CONSTRAINT time_slot_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 NOT NULL,
	user_name varchar(50) NOT NULL,
	"password" varchar(255) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_user_name_key UNIQUE (user_name)
);


-- public.classroom definition

-- Drop table

-- DROP TABLE public.classroom;

CREATE TABLE public.classroom (
	capacity int4 NOT NULL,
	building_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	room_number varchar(255) NOT NULL,
	CONSTRAINT classroom_pkey PRIMARY KEY (id),
	CONSTRAINT fkio8crqqepwi9ox33ui6enoi5x FOREIGN KEY (building_id) REFERENCES public.building(id)
);


-- public.student_group definition

-- Drop table

-- DROP TABLE public.student_group;

CREATE TABLE public.student_group (
	faculty_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_name varchar(255) NOT NULL,
	CONSTRAINT student_group_group_name_key UNIQUE (group_name),
	CONSTRAINT student_group_pkey PRIMARY KEY (id),
	CONSTRAINT fk7ufc9we1dv281aqjoe965od7h FOREIGN KEY (faculty_id) REFERENCES public.faculty(id)
);


-- public.subgroup definition

-- Drop table

-- DROP TABLE public.subgroup;

CREATE TABLE public.subgroup (
	group_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	subgroup_name varchar(255) NOT NULL,
	CONSTRAINT subgroup_pkey PRIMARY KEY (id),
	CONSTRAINT fkjfq59k7f75x27n22nlmxgtxq5 FOREIGN KEY (group_id) REFERENCES public.student_group(id)
);


-- public.teacher definition

-- Drop table

-- DROP TABLE public.teacher;

CREATE TABLE public.teacher (
	faculty_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	date_of_birth varchar(255) NULL,
	email varchar(255) NOT NULL,
	full_name varchar(255) NOT NULL,
	CONSTRAINT teacher_email_key UNIQUE (email),
	CONSTRAINT teacher_pkey PRIMARY KEY (id),
	CONSTRAINT fkqbtffr96yb132f3vi87okefkh FOREIGN KEY (faculty_id) REFERENCES public.faculty(id)
);


-- public.teacher_group definition

-- Drop table

-- DROP TABLE public.teacher_group;

CREATE TABLE public.teacher_group (
	group_id int8 NOT NULL,
	teacher_id int8 NOT NULL,
	CONSTRAINT teacher_group_pkey PRIMARY KEY (group_id, teacher_id),
	CONSTRAINT fkgqt1aiu9skxw0gyft8c8vph50 FOREIGN KEY (teacher_id) REFERENCES public.teacher(id),
	CONSTRAINT fkhd6c36il3tt1uvir0saa69yyn FOREIGN KEY (group_id) REFERENCES public.student_group(id)
);


-- public.user_roles definition

-- Drop table

-- DROP TABLE public.user_roles;

CREATE TABLE public.user_roles (
	role_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id),
	CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id),
	CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.lesson definition

-- Drop table

-- DROP TABLE public.lesson;

CREATE TABLE public.lesson (
	classroom_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	schedule_id int8 NOT NULL,
	subject_id int8 NOT NULL,
	teacher_id int8 NOT NULL,
	time_slot_id int8 NOT NULL,
	week_type varchar(255) NULL,
	CONSTRAINT lesson_pkey PRIMARY KEY (id),
	CONSTRAINT lesson_week_type_check CHECK (((week_type)::text = ANY ((ARRAY['ODD'::character varying, 'EVEN'::character varying, 'BOTH'::character varying])::text[]))),
	CONSTRAINT fk16w428nxkq0r9dk93vqu1vdge FOREIGN KEY (classroom_id) REFERENCES public.classroom(id),
	CONSTRAINT fk7ydr23s8y9j6lip5qrngoymx4 FOREIGN KEY (subject_id) REFERENCES public.subject(id),
	CONSTRAINT fk9yhaoqrjxt5gwmn6icp1lf35n FOREIGN KEY (teacher_id) REFERENCES public.teacher(id),
	CONSTRAINT fkni07g89mm7l9g7k8vbu7lf5r FOREIGN KEY (schedule_id) REFERENCES public.schedule(id),
	CONSTRAINT fkq8rsofdg8v58iakioenm8po0i FOREIGN KEY (time_slot_id) REFERENCES public.time_slot(id)
);


-- public.lesson_group definition

-- Drop table

-- DROP TABLE public.lesson_group;

CREATE TABLE public.lesson_group (
	group_id int8 NOT NULL,
	lesson_id int8 NOT NULL,
	CONSTRAINT lesson_group_pkey PRIMARY KEY (group_id, lesson_id),
	CONSTRAINT fk769lt252xdms1h6yhplk2n5eq FOREIGN KEY (lesson_id) REFERENCES public.lesson(id),
	CONSTRAINT fk8bsks01vndorv6uhpijxnm13s FOREIGN KEY (group_id) REFERENCES public.student_group(id)
);


-- public.lesson_subgroup definition

-- Drop table

-- DROP TABLE public.lesson_subgroup;

CREATE TABLE public.lesson_subgroup (
	lesson_id int8 NOT NULL,
	subgroup_id int8 NOT NULL,
	CONSTRAINT lesson_subgroup_pkey PRIMARY KEY (lesson_id, subgroup_id),
	CONSTRAINT fk9yeq3bgt0lqheyyp6dd5ksesm FOREIGN KEY (subgroup_id) REFERENCES public.subgroup(id),
	CONSTRAINT fkbxnfuwsbr5bm9g3qu1iwf0olx FOREIGN KEY (lesson_id) REFERENCES public.lesson(id)
);


-- public.student definition

-- Drop table

-- DROP TABLE public.student;

CREATE TABLE public.student (
	group_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	subgroup_id int8 NULL,
	date_of_birth varchar(255) NULL,
	email varchar(255) NOT NULL,
	full_name varchar(255) NOT NULL,
	CONSTRAINT student_email_key UNIQUE (email),
	CONSTRAINT student_pkey PRIMARY KEY (id),
	CONSTRAINT fkg1bvuko60ca7brx4xh8ehjtum FOREIGN KEY (subgroup_id) REFERENCES public.subgroup(id),
	CONSTRAINT fkqf0jwa26tqevbiu10cx0jggkf FOREIGN KEY (group_id) REFERENCES public.student_group(id)
);


-- public.lesson_student definitions

-- Drop table

-- DROP TABLE public.lesson_student;

CREATE TABLE public.lesson_student (
	lesson_id int8 NOT NULL,
	student_id int8 NOT NULL,
	CONSTRAINT lesson_student_pkey PRIMARY KEY (lesson_id, student_id),
	CONSTRAINT fk4t9i0s6y9ir1nteoi84tir9rb FOREIGN KEY (lesson_id) REFERENCES public.lesson(id),
	CONSTRAINT fkdkcwe8kn2g9p9olff5ojwlf18 FOREIGN KEY (student_id) REFERENCES public.student(id)
);